use std::fs::File;
use std::io::{BufRead, BufReader, Read, Seek, SeekFrom};
use std::path::{Path, PathBuf};
use std::time::UNIX_EPOCH;

use rusqlite::{params, Connection};

use crate::db::Db;

/// Lines read for metadata; cwd and the first prompt sit near the top.
const METADATA_LINES: usize = 200;
/// Title records are re-appended as a session goes on, so the tail has them.
const TITLE_TAIL_BYTES: u64 = 512 * 1024;
/// Transcripts larger than this are indexed from their tail only.
const INDEX_MAX_BYTES: u64 = 12 * 1024 * 1024;
const PROMPT_MAX_CHARS: usize = 200;

#[derive(Clone, Default, serde::Serialize)]
pub struct SessionTitles {
    /// Set by `/rename` inside Claude Code.
    pub custom: Option<String>,
    /// Generated by Claude for the session.
    pub ai: Option<String>,
}

#[derive(serde::Serialize)]
pub struct SessionInfo {
    pub id: String,
    pub path: String,
    pub cwd: Option<String>,
    pub project: String,
    pub modified_at: u64,
    pub size_bytes: u64,
    pub first_prompt: Option<String>,
    pub git_branch: Option<String>,
    pub titles: SessionTitles,
    pub recap: Option<String>,
}

#[derive(serde::Serialize)]
pub struct SessionMatch {
    pub id: String,
    pub snippet: String,
}

fn projects_dir() -> Option<PathBuf> {
    Some(dirs::home_dir()?.join(".claude").join("projects"))
}

fn text_from_message(msg: &serde_json::Value) -> Option<String> {
    match msg.get("content")? {
        serde_json::Value::String(s) => Some(s.clone()),
        serde_json::Value::Array(blocks) => {
            let joined: Vec<&str> = blocks
                .iter()
                .filter(|b| b.get("type").and_then(|t| t.as_str()) == Some("text"))
                .filter_map(|b| b.get("text").and_then(|t| t.as_str()))
                .collect();
            if joined.is_empty() {
                None
            } else {
                Some(joined.join(" "))
            }
        }
        _ => None,
    }
}

fn truncate(s: &str, max: usize) -> String {
    let cleaned = s.split_whitespace().collect::<Vec<_>>().join(" ");
    if cleaned.chars().count() <= max {
        return cleaned;
    }
    cleaned.chars().take(max - 1).collect::<String>() + "…"
}

fn read_titles(path: &Path) -> SessionTitles {
    let mut titles = SessionTitles::default();
    let Ok(mut file) = File::open(path) else {
        return titles;
    };
    let Ok(len) = file.metadata().map(|m| m.len()) else {
        return titles;
    };
    let start = len.saturating_sub(TITLE_TAIL_BYTES);
    if file.seek(SeekFrom::Start(start)).is_err() {
        return titles;
    }
    let mut buf = String::new();
    if file
        .take(TITLE_TAIL_BYTES + 1)
        .read_to_string(&mut buf)
        .is_err()
    {
        return titles;
    }
    let body = if start > 0 {
        match buf.find('\n') {
            Some(i) => &buf[i + 1..],
            None => return titles,
        }
    } else {
        &buf[..]
    };
    for line in body.lines() {
        let Ok(v) = serde_json::from_str::<serde_json::Value>(line) else {
            continue;
        };
        match v.get("type").and_then(|t| t.as_str()) {
            Some("custom-title") => {
                titles.custom = v
                    .get("customTitle")
                    .and_then(|t| t.as_str())
                    .map(str::to_string)
            }
            Some("ai-title") => {
                titles.ai = v
                    .get("aiTitle")
                    .and_then(|t| t.as_str())
                    .map(str::to_string)
            }
            _ => {}
        }
    }
    titles
}

#[tauri::command]
pub fn session_titles(path: String) -> SessionTitles {
    read_titles(Path::new(&path))
}

fn read_metadata(path: &Path) -> (Option<String>, Option<String>, Option<String>) {
    let Ok(file) = File::open(path) else {
        return (None, None, None);
    };
    let (mut cwd, mut branch, mut prompt) = (None, None, None);
    for line in BufReader::new(file)
        .lines()
        .take(METADATA_LINES)
        .map_while(Result::ok)
    {
        let Ok(v) = serde_json::from_str::<serde_json::Value>(&line) else {
            continue;
        };
        if cwd.is_none() {
            cwd = v.get("cwd").and_then(|c| c.as_str()).map(str::to_string);
        }
        if branch.is_none() {
            branch = v
                .get("gitBranch")
                .and_then(|b| b.as_str())
                .filter(|b| !b.is_empty())
                .map(str::to_string);
        }
        if prompt.is_none() && v.get("type").and_then(|t| t.as_str()) == Some("user") {
            if let Some(text) = v.get("message").and_then(text_from_message) {
                if !text.starts_with('<') && !text.trim().is_empty() {
                    prompt = Some(truncate(&text, PROMPT_MAX_CHARS));
                }
            }
        }
        if cwd.is_some() && branch.is_some() && prompt.is_some() {
            break;
        }
    }
    (cwd, branch, prompt)
}

/// Conversation text only, so the search index stays far smaller than the file.
fn extract_body(path: &Path, size: u64) -> String {
    let Ok(mut file) = File::open(path) else {
        return String::new();
    };
    if size > INDEX_MAX_BYTES {
        let _ = file.seek(SeekFrom::Start(size - INDEX_MAX_BYTES));
    }
    let mut out = String::new();
    for line in BufReader::new(file).lines().map_while(Result::ok) {
        let Ok(v) = serde_json::from_str::<serde_json::Value>(&line) else {
            continue;
        };
        match v.get("type").and_then(|t| t.as_str()) {
            Some("user") | Some("assistant") => {
                if let Some(text) = v.get("message").and_then(text_from_message) {
                    out.push_str(&text);
                    out.push('\n');
                }
            }
            _ => {}
        }
    }
    out
}

/// Brings the index up to date for transcripts that changed since last time.
fn reindex(conn: &Connection) -> Result<(), String> {
    let root = projects_dir().ok_or("no home dir")?;
    let Ok(projects) = std::fs::read_dir(&root) else {
        return Ok(());
    };

    for project in projects.flatten() {
        if !project.file_type().map(|t| t.is_dir()).unwrap_or(false) {
            continue;
        }
        let project_name = project.file_name().to_string_lossy().to_string();
        let Ok(files) = std::fs::read_dir(project.path()) else {
            continue;
        };
        for entry in files.flatten() {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("jsonl") {
                continue;
            }
            let Ok(meta) = entry.metadata() else { continue };
            if meta.len() == 0 {
                continue;
            }
            let id = path
                .file_stem()
                .unwrap_or_default()
                .to_string_lossy()
                .to_string();
            let size = meta.len() as i64;
            let modified = meta
                .modified()
                .ok()
                .and_then(|m| m.duration_since(UNIX_EPOCH).ok())
                .map(|d| d.as_secs() as i64)
                .unwrap_or(0);

            let known: Option<i64> = conn
                .query_row(
                    "SELECT indexed_size FROM sessions WHERE id = ?1",
                    params![id],
                    |r| r.get(0),
                )
                .ok();
            if known == Some(size) {
                continue;
            }

            let titles = read_titles(&path);
            let (cwd, branch, prompt) = read_metadata(&path);
            conn.execute(
                "INSERT INTO sessions (id, path, project, cwd, custom_title, ai_title, first_prompt,
                                       git_branch, modified_at, size_bytes, indexed_size)
                 VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?10)
                 ON CONFLICT(id) DO UPDATE SET
                     path=excluded.path, project=excluded.project, cwd=excluded.cwd,
                     custom_title=excluded.custom_title, ai_title=excluded.ai_title,
                     first_prompt=excluded.first_prompt, git_branch=excluded.git_branch,
                     modified_at=excluded.modified_at, size_bytes=excluded.size_bytes,
                     indexed_size=excluded.indexed_size",
                params![
                    id,
                    path.to_string_lossy(),
                    project_name,
                    cwd,
                    titles.custom,
                    titles.ai,
                    prompt,
                    branch,
                    modified,
                    size
                ],
            )
            .map_err(|e| e.to_string())?;

            let body = extract_body(&path, meta.len());
            let _ = conn.execute(
                "DELETE FROM sessions_fts WHERE session_id = ?1",
                params![id],
            );
            let _ = conn.execute(
                "INSERT INTO sessions_fts (session_id, body) VALUES (?1, ?2)",
                params![id, body],
            );
        }
    }
    Ok(())
}

fn row_to_info(row: &rusqlite::Row) -> rusqlite::Result<SessionInfo> {
    Ok(SessionInfo {
        id: row.get(0)?,
        path: row.get(1)?,
        project: row.get::<_, Option<String>>(2)?.unwrap_or_default(),
        cwd: row.get(3)?,
        titles: SessionTitles {
            custom: row.get(4)?,
            ai: row.get(5)?,
        },
        first_prompt: row.get(6)?,
        git_branch: row.get(7)?,
        modified_at: row.get::<_, i64>(8)? as u64,
        size_bytes: row.get::<_, i64>(9)? as u64,
        recap: row.get(10)?,
    })
}

const SELECT: &str = "SELECT id, path, project, cwd, custom_title, ai_title, first_prompt,
                             git_branch, modified_at, size_bytes, recap FROM sessions";

#[tauri::command]
pub fn sessions_list(db: tauri::State<Db>) -> Result<Vec<SessionInfo>, String> {
    let conn = db.0.lock().unwrap();
    reindex(&conn)?;
    let sql = format!("{SELECT} ORDER BY modified_at DESC");
    let mut stmt = conn.prepare(&sql).map_err(|e| e.to_string())?;
    let rows = stmt.query_map([], row_to_info).map_err(|e| e.to_string())?;
    rows.collect::<rusqlite::Result<Vec<_>>>()
        .map_err(|e| e.to_string())
}

/// Full-text search over the indexed conversation bodies.
#[tauri::command]
pub fn sessions_search(
    db: tauri::State<Db>,
    query: String,
    limit: Option<usize>,
) -> Result<Vec<SessionMatch>, String> {
    let needle = query.trim();
    if needle.chars().count() < 2 {
        return Ok(Vec::new());
    }
    let conn = db.0.lock().unwrap();
    // Quoted so punctuation in the query cannot be read as FTS syntax.
    let phrase = format!("\"{}\"", needle.replace('"', ""));
    let mut stmt = conn
        .prepare(
            "SELECT session_id, snippet(sessions_fts, 1, '', '', '…', 18)
             FROM sessions_fts WHERE sessions_fts MATCH ?1 LIMIT ?2",
        )
        .map_err(|e| e.to_string())?;
    let rows = stmt
        .query_map(params![phrase, limit.unwrap_or(60) as i64], |r| {
            Ok(SessionMatch {
                id: r.get(0)?,
                snippet: r.get(1)?,
            })
        })
        .map_err(|e| e.to_string())?;
    rows.collect::<rusqlite::Result<Vec<_>>>()
        .map_err(|e| e.to_string())
}
